version: '3'

services:
  web:
    restart: always
    build:
        context: .
    container_name: expense_tracker_container
    command: sh /opt/app/backend/run.sh
    ports:
      [8010:8002]
    volumes:
      - /home/ubuntu/ExpenseTracker-backend/DockerData/static:/opt/app/backend/static/ #for static files
      - /home/ubuntu/ExpenseTracker-backend/DockerData/media:/opt/app/backend/media/ #for media files