version: '3'

services:
  web:
    restart: unless-stopped
    env_file: .env
    build:
        context: .
    command: sh /opt/app/backend/run.sh
    ports:
      [8010:8000]
    volumes:
      - /home/ubuntu/ExpenseTracker/DockerData/static:/opt/app/backend/static/ #for static files
      - /home/ubuntu/ExpenseTracker/DockerData/media:/opt/app/backend/media/ #for media files
