version: "3"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - ./DockerData/postgres:/var/lib/postgresql/data
    env_file:
      - .pgenv

  web:
    build:
      context: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    entrypoint: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]

  redis:
    image: redis:6.2-alpine
    command: redis-server

  celery:
    build:
      context: .
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
      - redis
    entrypoint: sh /code/celery.sh
