# Generated by Django 3.0.7 on 2021-06-12 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('slug', models.SlugField(editable=False, verbose_name='Slug')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='_type',
            field=models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], default='DEBIT', editable=False, max_length=50, verbose_name='Type'),
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.AccountBook', verbose_name='Owner'),
        ),
    ]
