# Generated by Django 3.0.7 on 2021-06-12 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210612_0749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountbook',
            old_name='name',
            new_name='title',
        ),
    ]
