# Generated by Django 3.0.7 on 2021-06-26 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210612_1145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credit',
        ),
        migrations.DeleteModel(
            name='Debit',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='_type',
            field=models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.AccountBook', verbose_name='Account Book'),
        ),
    ]
