# Generated by Django 3.0.7 on 2021-09-14 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210626_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountbook',
            options={'ordering': ['-id']},
        ),
    ]
